version: '3.3'

services:
  db:
    image: mariadb:10.4.5
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: strapi
      MYSQL_USER: tsuyoshi
      MYSQL_PASSWORD: password
    ports:
      - '3306:3306'
    volumes:
      - ./db/mysql_data:/var/lib/mysql

# volumes:
#   db_data: {}